### ISSUE TITLE
[BUG] filtering on task or project for `tw_gcal_sync` seems to have no effect

### ISSUE THREAD

**Issue by jemorriso** [bergercookie/syncall#115] opened 2024-05-08 05:55 UTC
### Describe the bug

When I run `tw_gcal_sync -t task3 -c test3` all taskwarrior tasks with due dates are synced to the 'task3' google calendar, regardless of whether they have the 'task3' tag or not.

## To Reproduce

```shell
task add test task 2 due:tom+13h
task add test task 3 due:tom+13h +task3
tw_gcal_sync -t task3 -c test3
```

### Expected Behavior

Only task 2 should show up on the test3 calendar.

#### OS Version (`cat /etc/*-release; uname -a`)

Darwin Jeremys-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

#### Python version (`python --version; python3 --version`)

python 3.11.7

#### `--version` of your executable

tw_gcal_sync, version <module 'syncall.version' from '/Users/jerry/venvs/syncall/.venv/lib/python3.11/site-packages/syncall/version.py'>

**Comment by bergercookie** [comment] 2024-08-12 07:29
> Only task 2 should show up on the test3 calendar.

You probably meant to sync only the `test task 3` task from your example, right?

In any case, I cannot reproduce it on my end.
Could you test it with the latest published releaes from PyPI?

**Comment by bergercookie** [comment] 2024-08-15 06:49
I'll close this for now but if it persists, let me know and I'll re-open

**Closed by bergercookie** 2024-08-15 06:49 UTC
Labels: bug, taskwarrior
