### ISSUE TITLE
[BUG] Cannot run sync twice on TW<->CalDAV

### ISSUE THREAD

**Issue by RaitoBezarius** [bergercookie/syncall#99] opened 2023-09-15 23:24 UTC
### Describe the bug

On second restart of synchronization, I get a crash with the following trace: https://gist.github.com/RaitoBezarius/4af81a60c5736dbabc44b71e975b9ebe

### To Reproduce

I run the following script:

```
#!/nix/store/vqvj60h076bhqj6977caz0pfxs6543nb-bash-5.2-p15/bin/bash
set -o errexit
set -o nounset
set -o pipefail

export PATH="/nix/store/iz4dlydb7paz2f8xi0dfk6kfdmhm7d4c-gnupg-2.4.1/bin:$PATH"

export TASKRC=/home/raito/.config/task/taskrc
/nix/store/5kwpflid12cs3gxdc8vzg7sdgdw8826k-syncall-1.5.1/bin/tw_caldav_sync \
  --caldav-calendar TODO \
  --caldav-url https://redacted/remote.php/dav \
  --caldav-user raito \
  --caldav-passwd-pass-path /nix/store/qzy8q7j8ig8086pkbjszh6x0kxg3qzdl-kachpass/bin/kachpass \
  --caldav-passwd Private/nextCloud/twsync \
  --resolution-strategy MostRecentRS \
  --taskwarrior-tags sync-caldav \
```

twice.

kachpass is just a sophisticated `pass` interface with caching with kernel keyring.

### Expected Behavior

The second time it should also work and continue sync.

#### OS Version (`cat /etc/*-release; uname -a`)

NixOS 23.11pre526036.3b1f3712a415 (Tapir).

#### Python version (`python --version; python3 --version`)

3.10.12

#### `--version` of your executable

tw_caldav_sync, version 1.5.1

(I am the packager of syncall in nixpkgs.)

### Additional context

Contents of the YAML:

```
❯ cat ~/.config/syncall/TODO__None__sync-caldav__False__False.yaml
Tw_caldav_ids: !!python/object/apply:bidict._base._from_other
- !!python/name:bidict.bidict ''
- {}
- false
```

**Comment by bergercookie** [comment] 2023-12-31 17:18
Hi @RaitoBezarius sorry for the delay and thanks for shipping this tool to `NixOS` :)

This looks like an issue with PyYAML, not with `syncall` or `bubop` per se.
Could you dump the list of python packages and their versions ?  e.g., with `pip3 freeze`

**Comment by doronbehar** [comment] 2024-06-12 23:46
I too encountered this issue here on NixOS, and I tried to install syncall with pyyaml5.3.1 and it didn't help either. (@RaitoBezarius my branch is available [here](https://github.com/doronbehar/nixpkgs/pull/new/WIP/syncall)). In my case this wasn't even related to running it twice, it simply failed to run for the first time...

**Comment by doronbehar** [comment] 2024-06-13 08:36
I made another attempt to use all of the dependencies pinned, and I encountered other errors.. so I will no longer put my efforts on this.

https://github.com/NixOS/nixpkgs/pull/319519

**Comment by bergercookie** [comment] 2024-08-16 11:05
I cannot reproduce this issue unfortunately with syncall 1.8.7 + PyYAML 5.3.1, bidict 0.21.4.
If you can provide me with a set of commands I can reproduce it with I'm happy to look at it further.

> I too encountered this issue here on NixOS, and I tried to install syncall with pyyaml5.3.1 and it didn't help either. (@RaitoBezarius my branch is available [here](https://github.com/doronbehar/nixpkgs/pull/new/WIP/syncall)). In my case this wasn't even related to running it twice, it simply failed to run for the first time...

> https://github.com/doronbehar/nixpkgs/pull/new/WIP/syncall

This redirects to a new PR page to the nixpkgs repo. Probably there was a paste error here @doronbehar

**Comment by bergercookie** [comment] 2024-08-16 11:06
Closing this as I cannot repro but can re-open on new information :)

**Closed by bergercookie** 2024-08-16 11:06 UTC
Labels: bug, tw_caldav_sync

**Comment by doronbehar** [comment] 2024-08-16 15:41
> > [doronbehar/nixpkgs/pull/new/WIP/syncall](https://github.com/doronbehar/nixpkgs/pull/new/WIP/syncall)
> 
> This redirects to a new PR page to the nixpkgs repo. Probably there was a paste error here @doronbehar

Not a paste error. If you'd scroll down a bit you can see the dependencies I tried to pin.

> syncall 1.8.7 + PyYAML 5.3.1, bidict 0.21.4.

I didn't pin bidict to this version though, so this might be what I missed. I don't have time now to put my efforts into trying again though, sorry. In anycase, it'd be nice if syncall would have been updated to support the new API of all of these libraries...

**Comment by niksingh710** [comment] 2024-11-19 10:34
@RaitoBezarius the package installs fine.
below is the error that i am facing.
```sh
󰘧 tw_gtasks_sync
2024-11-19 16:03:05.172 | ERROR    | syncall.app_utils:inform_about_app_extras:242 -
You have to install the google,tw extras for tw_gtasks_sync to work.
With pip, you can do it with something like: "pip3 install syncall[google,tw]"
Exiting.
```

**Comment by oneacik** [comment] 2024-12-29 13:24
Remember to remove ~/.config/syncall/ while testing, so it doesn't read corrupted files.

**Comment by shymega** [comment] 2025-04-15 17:41
@bergercookie I'm working on fixing the Nixpkgs derivation for Syncall, and making it support optional features, as well as reintroducing Google Keep and Notion.

However, currently it's broken due to #99 - i.e, this issue.

Can we get this fixed at some point? It's blocking me adding a Flake to this repo as well.
