### ISSUE TITLE
[BUG] Failed to parse UUID for task

### ISSUE THREAD

**Issue by speyejack** [bergercookie/syncall#95] opened 2023-08-22 05:19 UTC
22:09:14.53 | DEBUG    	| Initialising...
22:09:14.53 | DEBUG    	| Initialising preferences manager -> /home/jack/.config/syncall
22:09:14.53 | INFO     	| Loading preferences...
22:09:14.53 | DEBUG    	| Loading cached configuration - TaskWarrior__None__+cal
22:09:14.53 | INFO     	|

Configuration:
===============

  - TW Tags               : ('+cal',)
  - TW Project            : None
  - Google Calendar       : TaskWarrior
  - Prefer scheduled dates: True

22:09:14.55 | DEBUG    	| Using a custom configuration file ... -> TaskWarrior__None__+cal
22:09:14.55 | DEBUG    	| Initialising preferences manager -> /home/jack/.config/syncall
22:09:14.55 | INFO     	| Loading preferences...
22:09:14.55 | DEBUG    	| Connecting to Google Calendar...
22:09:14.55 | INFO     	| Using already cached credentials...
22:09:15.17 | DEBUG    	| Connected to Google Calendar.
22:09:15.17 | INFO     	| Initializing Taskwarrior...
22:09:15.40 | ERROR    	| Application failed; Below you can find the error message and stack trace. If you think this is a bug, attach this stack trace to create a new issue -> [https://github.com/bergercookie/syncall/issues].
Traceback (most recent call last):

  File "/home/jack/.local/bin/tw_gcal_sync", line 8, in <module>
    sys.exit(main())
    │   │    └ <Command main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/jack/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f7292517700>
           └ <Command main>
  File "/home/jack/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f7293301fa0>
         │    └ <function Command.invoke at 0x7f729251a1f0>
         └ <Command main>
  File "/home/jack/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'prefer_scheduled_date': True, 'tw_tags': ('+cal',), 'gcal_calendar': 'TaskWarrior', 'google_secret': '/home/jack/client_sec...
           │   │      │    │           └ <click.core.Context object at 0x7f7293301fa0>
           │   │      │    └ <function main at 0x7f729188c4c0>
           │   │      └ <Command main>
           │   └ <function Context.invoke at 0x7f7292511f70>
           └ <click.core.Context object at 0x7f7293301fa0>
  File "/home/jack/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'prefer_scheduled_date': True, 'tw_tags': ('+cal',), 'gcal_calendar': 'TaskWarrior', 'google_secret': '/home/jack/client_sec...
                       └ ()
> File "/home/jack/.local/lib/python3.9/site-packages/syncall/scripts/tw_gcal_sync.py", line 208, in main
    aggregator.sync()
    │          └ <function Aggregator.sync at 0x7f7292583790>
    └ <syncall.aggregator.Aggregator object at 0x7f72918fc8b0>
  File "/home/jack/.local/lib/python3.9/site-packages/syncall/aggregator.py", line 173, in sync
    str(item[self._helper_B.id_key]): item for item in self._side_B.get_all_items()
             │    │         │                          │    │       └ <function TaskWarriorSide.get_all_items at 0x7f72921c31f0>
             │    │         │                          │    └ <syncall.taskwarrior.taskwarrior_side.TaskWarriorSide object at 0x7f729188bdf0>
             │    │         │                          └ <syncall.aggregator.Aggregator object at 0x7f72918fc8b0>
             │    │         └ 'uuid'
             │    └ SideHelper(name='Tw', id_key='uuid', summary_key='description', other=SideHelper(name='Gcal', id_key='id', summary_key='summa...
             └ <syncall.aggregator.Aggregator object at 0x7f72918fc8b0>
  File "/home/jack/.local/lib/python3.9/site-packages/syncall/taskwarrior/taskwarrior_side.py", line 127, in get_all_items
    self._load_all_items()
    │    └ <function TaskWarriorSide._load_all_items at 0x7f72921c3160>
    └ <syncall.taskwarrior.taskwarrior_side.TaskWarriorSide object at 0x7f729188bdf0>
  File "/home/jack/.local/lib/python3.9/site-packages/syncall/taskwarrior/taskwarrior_side.py", line 103, in _load_all_items
    tasks = self._tw.load_tasks()
            │    │   └ <function TaskWarriorShellout.load_tasks at 0x7f7292235700>
            │    └ <taskw.warrior.TaskWarriorShellout object at 0x7f72918fc700>
            └ <syncall.taskwarrior.taskwarrior_side.TaskWarriorSide object at 0x7f729188bdf0>
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/warrior.py", line 596, in load_tasks
    results = dict(
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/warrior.py", line 597, in <genexpr>
    (db, self._get_task_objects('status:%s' % db, 'export'))
     │   │    │                               └ 'pending'
     │   │    └ <function TaskWarriorShellout._get_task_objects at 0x7f72922353a0>
     │   └ <taskw.warrior.TaskWarriorShellout object at 0x7f72918fc700>
     └ 'pending'
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/warrior.py", line 529, in _get_task_objects
    value = [self._get_task_object(j) for j in json]
             │    │                            └ [{'id': 1, 'description': 'Create a gotify notify for tasks and due', 'energy': 'M', 'entry': '20230707T103807Z', 'est': 'M',...
             │    └ <function TaskWarriorShellout._get_task_object at 0x7f7292235430>
             └ <taskw.warrior.TaskWarriorShellout object at 0x7f72918fc700>
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/warrior.py", line 529, in <listcomp>
    value = [self._get_task_object(j) for j in json]
             │    │                │      │    └ <module 'json' from '/usr/lib/python3.9/json/__init__.py'>
             │    │                │      └ {'id': 5, 'depends': '["d69dba34-1379-4073-8564-334a13e3317f"]', 'description': 'Test magneto board', 'energy': 'M', 'entry':...
             │    │                └ {'id': 5, 'depends': '["d69dba34-1379-4073-8564-334a13e3317f"]', 'description': 'Test magneto board', 'energy': 'M', 'entry':...
             │    └ <function TaskWarriorShellout._get_task_object at 0x7f7292235430>
             └ <taskw.warrior.TaskWarriorShellout object at 0x7f72918fc700>
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/warrior.py", line 534, in _get_task_object
    return Task(obj, udas=self.config.get_udas())
           │    │         │    │      └ <function TaskRc.get_udas at 0x7f729222fca0>
           │    │         │    └ {'data': {'location': '/home/jack/.task'}, 'news': {'version': '2.6.0'}, 'taskd': {'server': 'task.fn.je:53589', 'certificate...
           │    │         └ <taskw.warrior.TaskWarriorShellout object at 0x7f72918fc700>
           │    └ {'id': 5, 'depends': '["d69dba34-1379-4073-8564-334a13e3317f"]', 'description': 'Test magneto board', 'energy': 'M', 'entry':...
           └ <class 'taskw.task.Task'>
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/task.py", line 77, in __init__
    processed[k] = self._deserialize(k, v, self._fields)
    │         │    │    │            │  │  │    └ {'annotations': <AnnotationArrayField 'Annotations'>, 'depends': <CommaSeparatedUUIDField 'Depends Upon'>, 'description': <St...
    │         │    │    │            │  │  └ {}
    │         │    │    │            │  └ '["d69dba34-1379-4073-8564-334a13e3317f"]'
    │         │    │    │            └ 'depends'
    │         │    │    └ <classmethod object at 0x7f729222cd90>
    │         │    └ {}
    │         └ 'depends'
    └ {'id': 5}
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/task.py", line 126, in _deserialize
    return converter.deserialize(value)
           │         │           └ '["d69dba34-1379-4073-8564-334a13e3317f"]'
           │         └ <function CommaSeparatedUUIDField.deserialize at 0x7f7292227550>
           └ <CommaSeparatedUUIDField 'Depends Upon'>
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/fields/commaseparateduuid.py", line 23, in deserialize
    return DirtyableList([uuid.UUID(v) for v in value])
           │              │    │                └ ['["d69dba34-1379-4073-8564-334a13e3317f"]']
           │              │    └ <class 'uuid.UUID'>
           │              └ <module 'uuid' from '/usr/lib/python3.9/uuid.py'>
           └ <class 'taskw.fields.base.DirtyableList'>
  File "/home/jack/.local/lib/python3.9/site-packages/taskw/fields/commaseparateduuid.py", line 23, in <listcomp>
    return DirtyableList([uuid.UUID(v) for v in value])
           │              │    │    │      └ '["d69dba34-1379-4073-8564-334a13e3317f"]'
           │              │    │    └ '["d69dba34-1379-4073-8564-334a13e3317f"]'
           │              │    └ <class 'uuid.UUID'>
           │              └ <module 'uuid' from '/usr/lib/python3.9/uuid.py'>
           └ <class 'taskw.fields.base.DirtyableList'>
  File "/usr/lib/python3.9/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')

ValueError: badly formed hexadecimal UUID string

### Describe the bug

It looks like taskw fails to parse the UUID used for tasks

### To Reproduce

Run tw_gcal_sync, after logging into google it should fail

### Expected Behavior

Sync to Google

#### OS Version (`cat /etc/*-release; uname -a`)
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Linux Debian 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

#### Python version (`python --version; python3 --version`)

Python 3.9.2

#### `--version` of your executable

E.g., with `tw_gcal_sync`, provide the output of `tw_gcal_sync --version`:

tw_gcal_sync, version 1.5.1

### Additional context

It looks like its related to taskw but I didnt see any issues corrisponding to hex parsing there.

**Comment by bergercookie** [comment] 2023-12-31 20:55
I have managed to reproduce this but I'll need to do some more digging into why this issue occurs.

> It looks like its related to taskw but I didnt see any issues corrisponding to hex parsing there.

This does sound reasonable.
One more reason for implementing for using a different taskwarrior python wrapper (see https://github.com/bergercookie/syncall/issues/65)

**Comment by bergercookie** [comment] 2024-01-29 10:45
@speyejack , I'm struggling to figure out the conditions where this is triggered. Do you know how you've ended up with this issue in the first place ? What was the taskwarrior CLI command(s) you executed for this issue to be triggered? You 've probably added a dependency of one task onto another since this issue `depends`  CommaSeparatedUUIDField

**Comment by bergercookie** [comment] 2024-01-31 08:08
I have not found a way to reliably reproduce this so I'll close this for now. My intuition says that maybe this was an issue with the tw server or with a taskwarrior client < 2.5. In recent TW versions the `depends` is exported as a list of strings so this bug shouldn't reproduce there.

**Closed** 2024-01-31 08:08 UTC
Labels: bug, tw_gcal_sync, third-party-bug
